"""empty message

Revision ID: 4b930f9cc76d
Revises: 602aea728911
Create Date: 2021-04-21 09:42:51.734699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b930f9cc76d'
down_revision = '602aea728911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_answer_relation')
    op.add_column('answers', sa.Column('finish', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'finish')
    op.create_table('test_answer_relation',
    sa.Column('answer_id', sa.INTEGER(), nullable=True),
    sa.Column('test_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], )
    )
    # ### end Alembic commands ###
